run:
  timeout: 5m
  go: "1.22"

linters:
  enable:
    - errcheck
    - gofmt
    - govet
    - staticcheck
    - unused
    - gosimple

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

output:
  formats: colored-line-number
  print-issued-lines: true
  print-linter-name: true
