services:
  postgres:
    image: postgres:15-alpine
    container_name: gin-api-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: gin_api_server
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gin-api-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: gin-api-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres
    networks:
      - gin-api-network

volumes:
  postgres_data:

networks:
  gin-api-network:
    driver: bridge
